eureka:
 instance:
  client:
   service-url:
    defaultZone: http://localhost:8761/eureka/
 hostname: localhost

 microservice:
 payment-service:
  endpoints:
   endpoint:
    url:  http://PAYMENT-SERVICE/payment/doPayment

 order-service:
  endpoints:
   endpoint:
    url:  http://ORDER-SERVICE/order/bookOrder
